"""Curated list of legendary cycling cols/summits."""
FAMOUS_COLS = [
    {
        "id": "col-du-galibier",
        "name": "Col du Galibier",
        "region": "French Alps",
        "country": "France",
        "elevation": 2642,
        "distance_km": 18.1,
        "avg_gradient": 6.9,
        "max_gradient": 12.1,
        "lat": 45.0641,
        "lng": 6.4079,
        "category": "HC",
        "history": "Tour de France legend — first climbed in 1911.",
    },
    {
        "id": "mont-ventoux",
        "name": "Mont Ventoux",
        "region": "Provence",
        "country": "France",
        "elevation": 1909,
        "distance_km": 21.4,
        "avg_gradient": 7.5,
        "max_gradient": 12.0,
        "lat": 44.1741,
        "lng": 5.2783,
        "category": "HC",
        "history": "The Giant of Provence — barren lunar summit.",
    },
    {
        "id": "alpe-dhuez",
        "name": "Alpe d'Huez",
        "region": "French Alps",
        "country": "France",
        "elevation": 1860,
        "distance_km": 13.8,
        "avg_gradient": 8.1,
        "max_gradient": 13.0,
        "lat": 45.0909,
        "lng": 6.0703,
        "category": "HC",
        "history": "21 iconic hairpins — a Tour de France ritual.",
    },
    {
        "id": "passo-dello-stelvio",
        "name": "Passo dello Stelvio",
        "region": "Eastern Alps",
        "country": "Italy",
        "elevation": 2758,
        "distance_km": 24.3,
        "avg_gradient": 7.4,
        "max_gradient": 14.0,
        "lat": 46.5285,
        "lng": 10.4534,
        "category": "HC",
        "history": "48 numbered switchbacks — the Cima Coppi of the Giro.",
    },
    {
        "id": "col-du-tourmalet",
        "name": "Col du Tourmalet",
        "region": "Pyrenees",
        "country": "France",
        "elevation": 2115,
        "distance_km": 19.0,
        "avg_gradient": 7.4,
        "max_gradient": 10.2,
        "lat": 42.9083,
        "lng": 0.1450,
        "category": "HC",
        "history": "The Circle of Death — most-climbed Pyrenean pass.",
    },
    {
        "id": "passo-gavia",
        "name": "Passo Gavia",
        "region": "Lombardy Alps",
        "country": "Italy",
        "elevation": 2621,
        "distance_km": 25.6,
        "avg_gradient": 5.5,
        "max_gradient": 16.0,
        "lat": 46.3441,
        "lng": 10.4903,
        "category": "HC",
        "history": "1988 Giro snowstorm — Andy Hampsten's legend.",
    },
    {
        "id": "sa-calobra",
        "name": "Sa Calobra",
        "region": "Mallorca",
        "country": "Spain",
        "elevation": 682,
        "distance_km": 9.4,
        "avg_gradient": 7.0,
        "max_gradient": 12.0,
        "lat": 39.8497,
        "lng": 2.8003,
        "category": "1",
        "history": "The Snake — a spiral cut into the Serra de Tramuntana.",
    },
    {
        "id": "mortirolo",
        "name": "Passo del Mortirolo",
        "region": "Lombardy Alps",
        "country": "Italy",
        "elevation": 1852,
        "distance_km": 12.4,
        "avg_gradient": 10.5,
        "max_gradient": 18.0,
        "lat": 46.2247,
        "lng": 10.2947,
        "category": "HC",
        "history": "The hardest climb Lance ever rode, per Armstrong.",
    },
    {
        "id": "grossglockner",
        "name": "Grossglockner Hochalpenstrasse",
        "region": "Austrian Alps",
        "country": "Austria",
        "elevation": 2504,
        "distance_km": 24.3,
        "avg_gradient": 8.0,
        "max_gradient": 14.0,
        "lat": 47.0782,
        "lng": 12.8286,
        "category": "HC",
        "history": "Austria's highest paved alpine road.",
    },
    {
        "id": "teide",
        "name": "Mount Teide (El Teide)",
        "region": "Canary Islands",
        "country": "Spain",
        "elevation": 2200,
        "distance_km": 38.0,
        "avg_gradient": 5.0,
        "max_gradient": 9.0,
        "lat": 28.2724,
        "lng": -16.6425,
        "category": "HC",
        "history": "Volcanic climb — WorldTour winter training staple.",
    },
    {
        "id": "pikes-peak",
        "name": "Pikes Peak",
        "region": "Rocky Mountains",
        "country": "USA",
        "elevation": 4302,
        "distance_km": 39.0,
        "avg_gradient": 6.7,
        "max_gradient": 10.5,
        "lat": 38.8409,
        "lng": -105.0442,
        "category": "HC",
        "history": "America's Mountain — highest paved road summit.",
    },
    {
        "id": "col-de-liseran",
        "name": "Col de l'Iseran",
        "region": "French Alps",
        "country": "France",
        "elevation": 2764,
        "distance_km": 47.8,
        "avg_gradient": 4.1,
        "max_gradient": 12.0,
        "lat": 45.4173,
        "lng": 7.0311,
        "category": "HC",
        "history": "Highest paved pass in the Alps.",
    },
    {
        "id": "col-agnel",
        "name": "Col Agnel",
        "region": "Cottian Alps",
        "country": "France/Italy",
        "elevation": 2744,
        "distance_km": 20.5,
        "avg_gradient": 6.6,
        "max_gradient": 14.0,
        "lat": 44.6844,
        "lng": 6.9781,
        "category": "HC",
        "history": "Third-highest paved pass in the Alps.",
    },
    {
        "id": "angliru",
        "name": "Alto de l'Angliru",
        "region": "Asturias",
        "country": "Spain",
        "elevation": 1573,
        "distance_km": 12.5,
        "avg_gradient": 10.1,
        "max_gradient": 23.5,
        "lat": 43.2225,
        "lng": -5.9422,
        "category": "HC",
        "history": "Brutal Vuelta finish — 23.5% ramps at La Cueña les Cabres.",
    },
    {
        "id": "zoncolan",
        "name": "Monte Zoncolan",
        "region": "Carnic Alps",
        "country": "Italy",
        "elevation": 1750,
        "distance_km": 10.1,
        "avg_gradient": 11.9,
        "max_gradient": 22.0,
        "lat": 46.5017,
        "lng": 12.9758,
        "category": "HC",
        "history": "The Kaiser — Europe's steepest paved climb.",
    },
]
