"""Curated list of legendary cycling cols/summits, each with 1+ climb sides."""

FAMOUS_COLS = [
    {
        "id": "col-du-galibier",
        "name": "Col du Galibier",
        "region": "French Alps",
        "country": "France",
        "elevation": 2642,
        "lat": 45.0641,
        "lng": 6.4079,
        "category": "HC",
        "history": "Tour de France legend — first climbed in 1911.",
        "sides": [
            {"name": "Valloire (north)", "start_lat": 45.1666, "start_lng": 6.4283,
             "distance_km": 18.1, "avg_gradient": 6.9, "max_gradient": 12.1},
            {"name": "Col du Lautaret (south)", "start_lat": 45.0341, "start_lng": 6.4041,
             "distance_km": 8.5, "avg_gradient": 6.9, "max_gradient": 12.1},
        ],
    },
    {
        "id": "mont-ventoux",
        "name": "Mont Ventoux",
        "region": "Provence",
        "country": "France",
        "elevation": 1909,
        "lat": 44.1741,
        "lng": 5.2783,
        "category": "HC",
        "history": "The Giant of Provence — barren lunar summit.",
        "sides": [
            {"name": "Bédoin", "start_lat": 44.1225, "start_lng": 5.1806,
             "distance_km": 21.4, "avg_gradient": 7.5, "max_gradient": 12.0},
            {"name": "Malaucène", "start_lat": 44.1747, "start_lng": 5.1339,
             "distance_km": 21.2, "avg_gradient": 7.2, "max_gradient": 12.0},
            {"name": "Sault", "start_lat": 44.0908, "start_lng": 5.4108,
             "distance_km": 26.0, "avg_gradient": 4.5, "max_gradient": 11.0},
        ],
    },
    {
        "id": "alpe-dhuez",
        "name": "Alpe d'Huez",
        "region": "French Alps",
        "country": "France",
        "elevation": 1860,
        "lat": 45.0909,
        "lng": 6.0703,
        "category": "HC",
        "history": "21 iconic hairpins — a Tour de France ritual.",
        "sides": [
            {"name": "Bourg d'Oisans (classic)", "start_lat": 45.0530, "start_lng": 6.0272,
             "distance_km": 13.8, "avg_gradient": 8.1, "max_gradient": 13.0},
        ],
    },
    {
        "id": "passo-dello-stelvio",
        "name": "Passo dello Stelvio",
        "region": "Eastern Alps",
        "country": "Italy",
        "elevation": 2758,
        "lat": 46.5285,
        "lng": 10.4534,
        "category": "HC",
        "history": "48 numbered switchbacks — the Cima Coppi of the Giro.",
        "sides": [
            {"name": "Prato (48 hairpins)", "start_lat": 46.6169, "start_lng": 10.5931,
             "distance_km": 24.3, "avg_gradient": 7.4, "max_gradient": 14.0},
            {"name": "Bormio", "start_lat": 46.4681, "start_lng": 10.3722,
             "distance_km": 21.5, "avg_gradient": 7.1, "max_gradient": 14.0},
            {"name": "Umbrail (Swiss)", "start_lat": 46.5450, "start_lng": 10.4358,
             "distance_km": 13.4, "avg_gradient": 8.4, "max_gradient": 14.0},
        ],
    },
    {
        "id": "col-du-tourmalet",
        "name": "Col du Tourmalet",
        "region": "Pyrenees",
        "country": "France",
        "elevation": 2115,
        "lat": 42.9083,
        "lng": 0.1450,
        "category": "HC",
        "history": "The Circle of Death — most-climbed Pyrenean pass.",
        "sides": [
            {"name": "Luz-Saint-Sauveur (west)", "start_lat": 42.8722, "start_lng": -0.0072,
             "distance_km": 19.0, "avg_gradient": 7.4, "max_gradient": 10.2},
            {"name": "Sainte-Marie-de-Campan (east)", "start_lat": 42.9767, "start_lng": 0.2833,
             "distance_km": 17.2, "avg_gradient": 7.4, "max_gradient": 10.5},
        ],
    },
    {
        "id": "passo-gavia",
        "name": "Passo Gavia",
        "region": "Lombardy Alps",
        "country": "Italy",
        "elevation": 2621,
        "lat": 46.3441,
        "lng": 10.4903,
        "category": "HC",
        "history": "1988 Giro snowstorm — Andy Hampsten's legend.",
        "sides": [
            {"name": "Ponte di Legno (south)", "start_lat": 46.2588, "start_lng": 10.5109,
             "distance_km": 17.3, "avg_gradient": 7.9, "max_gradient": 16.0},
            {"name": "Bormio (north)", "start_lat": 46.4681, "start_lng": 10.3722,
             "distance_km": 25.6, "avg_gradient": 5.5, "max_gradient": 16.0},
        ],
    },
    {
        "id": "sa-calobra",
        "name": "Sa Calobra",
        "region": "Mallorca",
        "country": "Spain",
        "elevation": 682,
        "lat": 39.8497,
        "lng": 2.8003,
        "category": "1",
        "history": "The Snake — a spiral cut into the Serra de Tramuntana.",
        "sides": [
            {"name": "From the cove (only way up)", "start_lat": 39.8547, "start_lng": 2.8014,
             "distance_km": 9.4, "avg_gradient": 7.0, "max_gradient": 12.0},
        ],
    },
    {
        "id": "mortirolo",
        "name": "Passo del Mortirolo",
        "region": "Lombardy Alps",
        "country": "Italy",
        "elevation": 1852,
        "lat": 46.2247,
        "lng": 10.2947,
        "category": "HC",
        "history": "The hardest climb Lance ever rode, per Armstrong.",
        "sides": [
            {"name": "Mazzo di Valtellina", "start_lat": 46.2606, "start_lng": 10.2681,
             "distance_km": 12.4, "avg_gradient": 10.5, "max_gradient": 18.0},
            {"name": "Monno", "start_lat": 46.1892, "start_lng": 10.3439,
             "distance_km": 12.6, "avg_gradient": 7.6, "max_gradient": 16.0},
        ],
    },
    {
        "id": "grossglockner",
        "name": "Grossglockner Hochalpenstrasse",
        "region": "Austrian Alps",
        "country": "Austria",
        "elevation": 2504,
        "lat": 47.0782,
        "lng": 12.8286,
        "category": "HC",
        "history": "Austria's highest paved alpine road.",
        "sides": [
            {"name": "Bruck (north)", "start_lat": 47.2861, "start_lng": 12.8181,
             "distance_km": 27.4, "avg_gradient": 7.4, "max_gradient": 14.0},
            {"name": "Heiligenblut (south)", "start_lat": 47.0403, "start_lng": 12.8461,
             "distance_km": 15.3, "avg_gradient": 8.0, "max_gradient": 14.0},
        ],
    },
    {
        "id": "teide",
        "name": "Mount Teide (El Teide)",
        "region": "Canary Islands",
        "country": "Spain",
        "elevation": 2200,
        "lat": 28.2724,
        "lng": -16.6425,
        "category": "HC",
        "history": "Volcanic climb — WorldTour winter training staple.",
        "sides": [
            {"name": "La Orotava (north)", "start_lat": 28.3900, "start_lng": -16.5225,
             "distance_km": 38.0, "avg_gradient": 5.0, "max_gradient": 9.0},
            {"name": "Vilaflor (south)", "start_lat": 28.1567, "start_lng": -16.6367,
             "distance_km": 27.0, "avg_gradient": 5.4, "max_gradient": 9.0},
        ],
    },
    {
        "id": "pikes-peak",
        "name": "Pikes Peak",
        "region": "Rocky Mountains",
        "country": "USA",
        "elevation": 4302,
        "lat": 38.8409,
        "lng": -105.0442,
        "category": "HC",
        "history": "America's Mountain — highest paved road summit.",
        "sides": [
            {"name": "Cascade (classic)", "start_lat": 38.8983, "start_lng": -104.9722,
             "distance_km": 39.0, "avg_gradient": 6.7, "max_gradient": 10.5},
        ],
    },
    {
        "id": "col-de-liseran",
        "name": "Col de l'Iseran",
        "region": "French Alps",
        "country": "France",
        "elevation": 2764,
        "lat": 45.4173,
        "lng": 7.0311,
        "category": "HC",
        "history": "Highest paved pass in the Alps.",
        "sides": [
            {"name": "Bourg-Saint-Maurice (north)", "start_lat": 45.6197, "start_lng": 6.7708,
             "distance_km": 47.8, "avg_gradient": 4.1, "max_gradient": 12.0},
            {"name": "Bonneval-sur-Arc (south)", "start_lat": 45.3722, "start_lng": 7.0561,
             "distance_km": 13.4, "avg_gradient": 7.3, "max_gradient": 12.0},
        ],
    },
    {
        "id": "col-agnel",
        "name": "Col Agnel",
        "region": "Cottian Alps",
        "country": "France/Italy",
        "elevation": 2744,
        "lat": 44.6844,
        "lng": 6.9781,
        "category": "HC",
        "history": "Third-highest paved pass in the Alps.",
        "sides": [
            {"name": "Château-Ville-Vieille (French)", "start_lat": 44.7358, "start_lng": 6.8206,
             "distance_km": 20.5, "avg_gradient": 6.6, "max_gradient": 14.0},
            {"name": "Casteldelfino (Italian)", "start_lat": 44.6086, "start_lng": 7.0847,
             "distance_km": 21.0, "avg_gradient": 6.6, "max_gradient": 14.0},
        ],
    },
    {
        "id": "angliru",
        "name": "Alto de l'Angliru",
        "region": "Asturias",
        "country": "Spain",
        "elevation": 1573,
        "lat": 43.2225,
        "lng": -5.9422,
        "category": "HC",
        "history": "Brutal Vuelta finish — 23.5% ramps at La Cueña les Cabres.",
        "sides": [
            {"name": "La Vega (only way)", "start_lat": 43.2683, "start_lng": -5.9203,
             "distance_km": 12.5, "avg_gradient": 10.1, "max_gradient": 23.5},
        ],
    },
    {
        "id": "zoncolan",
        "name": "Monte Zoncolan",
        "region": "Carnic Alps",
        "country": "Italy",
        "elevation": 1750,
        "lat": 46.5017,
        "lng": 12.9758,
        "category": "HC",
        "history": "The Kaiser — Europe's steepest paved climb.",
        "sides": [
            {"name": "Ovaro (west)", "start_lat": 46.5450, "start_lng": 12.9769,
             "distance_km": 10.1, "avg_gradient": 11.9, "max_gradient": 22.0},
            {"name": "Sutrio (east)", "start_lat": 46.5111, "start_lng": 13.0122,
             "distance_km": 13.5, "avg_gradient": 9.8, "max_gradient": 21.0},
            {"name": "Priola (south)", "start_lat": 46.4636, "start_lng": 12.9469,
             "distance_km": 8.9, "avg_gradient": 9.6, "max_gradient": 20.0},
        ],
    },
]
